name: Build and Push Docker Image

on:
  push:
    branches:
      - docker  # Trigger on push to main branch
  pull_request:
    branches:
      - docker  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to DockerHub (or GitHub Container Registry)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add your DockerHub username in secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add your DockerHub password in secrets

    - name: Build Docker image
      run: |
        docker build -t nxtgencat/havelocscraper:${{ github.sha }} .

    - name: Push Docker image to DockerHub (or GitHub Container Registry)
      run: |
        docker push nxtgencat/havelocscraper:${{ github.sha }}
